version: '3.8'

services:
  build:
    container_name: passguard-build-desktop
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./build-tauri:/app/src-tauri/target/release/bundle