services:
  desktop-builds:
    build:
      # Specify the path to the Dockerfile
      context: .
      # Specify the Dockerfile to use for building the image
      dockerfile: Dockerfile.build

    # Mount a volume to store the built application artifacts
    volumes:
      # Map the local 'dist' directory to the directory where the built artifacts will be stored in the container
      - ./dist:/app/src-tauri/target/release/bundle
